spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: "/h2-console"
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: "sa"
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: -1
  ssl:
    enabled: false

armeria:
  ports:
    - port: 8443
      protocols: [ "http" ]
